/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};

/* C:(i0[3])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=-8.9999999999999997e-02;
  a1=9.8100000000000005e+00;
  a2=arg[0]? arg[0][0] : 0;
  a3=sin(a2);
  a3=(a1*a3);
  a0=(a0*a3);
  a4=-4.1999999999999996e-02;
  a5=arg[0]? arg[0][1] : 0;
  a6=cos(a5);
  a7=(a6*a3);
  a5=sin(a5);
  a2=cos(a2);
  a1=(a1*a2);
  a2=(a5*a1);
  a7=(a7+a2);
  a4=(a4*a7);
  a2=-9.3000000000000013e-02;
  a8=arg[0]? arg[0][2] : 0;
  a9=cos(a8);
  a10=(a9*a7);
  a8=sin(a8);
  a1=(a6*a1);
  a3=(a5*a3);
  a1=(a1-a3);
  a3=(a8*a1);
  a10=(a10+a3);
  a2=(a2*a10);
  a3=1.2000000000000000e-01;
  a11=(a3*a9);
  a12=9.4999999999999996e-01;
  a10=(a12*a10);
  a11=(a11*a10);
  a11=(a2-a11);
  a3=(a3*a8);
  a13=(a9*a1);
  a14=(a8*a7);
  a13=(a13-a14);
  a12=(a12*a13);
  a3=(a3*a12);
  a11=(a11+a3);
  a4=(a4+a11);
  a11=1.7999999999999999e-01;
  a6=(a11*a6);
  a3=6.9999999999999996e-01;
  a7=(a3*a7);
  a13=(a9*a10);
  a14=(a8*a12);
  a13=(a13-a14);
  a7=(a7+a13);
  a6=(a6*a7);
  a6=(a4-a6);
  a11=(a11*a5);
  a3=(a3*a1);
  a8=(a8*a10);
  a9=(a9*a12);
  a8=(a8+a9);
  a3=(a3+a8);
  a11=(a11*a3);
  a6=(a6+a11);
  a0=(a0+a6);
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a4;
  if (res[0]!=0) res[0][2]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int C(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int C_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int C_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void C_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int C_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void C_release(int mem) {
}

CASADI_SYMBOL_EXPORT void C_incref(void) {
}

CASADI_SYMBOL_EXPORT void C_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int C_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int C_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real C_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* C_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* C_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int C_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
